INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('clients_intel','email','text',NULL,'NO'),
	 ('clients_intel','source_id_1c','text',NULL,'YES'),
	 ('clients_intel','company_name','text',NULL,'YES'),
	 ('clients_intel','inn','text',NULL,'YES'),
	 ('clients_intel','ai_priority','integer',NULL,'YES'),
	 ('clients_intel','ai_summary','text',NULL,'YES'),
	 ('clients_intel','last_topic','text',NULL,'YES'),
	 ('clients_intel','current_status','text',NULL,'YES'),
	 ('clients_intel','next_followup_at','timestamp with time zone',NULL,'YES'),
	 ('clients_intel','updated_at','timestamp with time zone',NULL,'NO');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('email_match_results','id','bigint',NULL,'NO'),
	 ('email_match_results','message_id','text',NULL,'YES'),
	 ('email_match_results','matched_level','text',NULL,'NO'),
	 ('email_match_results','decision','text',NULL,'NO'),
	 ('email_match_results','decision_reason','text',NULL,'YES'),
	 ('email_match_results','contact_entity','text',NULL,'YES'),
	 ('email_match_results','contact_ref_key','uuid',NULL,'YES'),
	 ('email_match_results','owner_entity','text',NULL,'YES'),
	 ('email_match_results','owner_ref_key','uuid',NULL,'YES'),
	 ('email_match_results','confidence','numeric',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('email_match_results','matched_email','text',NULL,'YES'),
	 ('email_match_results','matched_phone','text',NULL,'YES'),
	 ('email_match_results','created_at','timestamp with time zone',NULL,'NO'),
	 ('email_messages','message_id','text',NULL,'NO'),
	 ('email_messages','from_email','text',NULL,'YES'),
	 ('email_messages','from_name','text',NULL,'YES'),
	 ('email_messages','subject','text',NULL,'YES'),
	 ('email_messages','received_at','timestamp with time zone',NULL,'YES'),
	 ('email_messages','source_mailbox','text',NULL,'YES'),
	 ('email_messages','raw_payload','jsonb',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('email_messages','created_at','timestamp with time zone',NULL,'NO'),
	 ('email_messages','is_junk','boolean',NULL,'NO'),
	 ('email_messages','junk_reason','text',NULL,'YES'),
	 ('email_messages','operator_comment','text',NULL,'YES'),
	 ('email_messages','thread_comment','text',NULL,'YES'),
	 ('email_messages','ai_summary','text',NULL,'YES'),
	 ('ingestion_cursors','source','text',NULL,'NO'),
	 ('ingestion_cursors','entity','text',NULL,'NO'),
	 ('ingestion_cursors','cursor_kind','text',NULL,'NO'),
	 ('ingestion_cursors','cursor_value','text',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('ingestion_cursors','cursor_meta','jsonb',NULL,'NO'),
	 ('ingestion_cursors','updated_at','timestamp with time zone',NULL,'NO'),
	 ('ingestion_event_log','event_id','bigint',NULL,'NO'),
	 ('ingestion_event_log','event_at','timestamp with time zone',NULL,'NO'),
	 ('ingestion_event_log','workflow_name','text',NULL,'NO'),
	 ('ingestion_event_log','mode','text',NULL,'YES'),
	 ('ingestion_event_log','event_type','text',NULL,'NO'),
	 ('ingestion_event_log','severity','text',NULL,'NO'),
	 ('ingestion_event_log','owner_ref_key','uuid',NULL,'YES'),
	 ('ingestion_event_log','contact_ref_key','uuid',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('ingestion_event_log','message','text',NULL,'YES'),
	 ('ingestion_event_log','details','jsonb',NULL,'NO'),
	 ('knowledge_base','id','bigint',NULL,'NO'),
	 ('knowledge_base','source_path','text',NULL,'NO'),
	 ('knowledge_base','source_section','text',NULL,'YES'),
	 ('knowledge_base','chunk_index','integer',NULL,'NO'),
	 ('knowledge_base','content','text',NULL,'NO'),
	 ('knowledge_base','category','text',NULL,'NO'),
	 ('knowledge_base','content_hash','text',NULL,'NO'),
	 ('knowledge_base','updated_at','timestamp with time zone',NULL,'NO');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('knowledge_base','is_active','boolean',NULL,'NO'),
	 ('onec_contacts','contact_entity','text',NULL,'NO'),
	 ('onec_contacts','contact_ref_key','uuid',NULL,'NO'),
	 ('onec_contacts','owner_entity','text',NULL,'YES'),
	 ('onec_contacts','owner_ref_key','uuid',NULL,'YES'),
	 ('onec_contacts','contact_name','text',NULL,'YES'),
	 ('onec_contacts','emails','ARRAY',NULL,'NO'),
	 ('onec_contacts','phones','ARRAY',NULL,'NO'),
	 ('onec_contacts','raw_payload','jsonb',NULL,'NO'),
	 ('onec_contacts','fetched_at','timestamp with time zone',NULL,'NO');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_contacts','contact_tags','jsonb',NULL,'NO'),
	 ('onec_contacts','contact_notes','text',NULL,'YES'),
	 ('onec_contacts','contact_is_primary','boolean',NULL,'YES'),
	 ('onec_contacts','contact_is_junk','boolean',NULL,'NO'),
	 ('onec_contacts','contact_junk_reason','text',NULL,'YES'),
	 ('onec_contacts','contact_role','text',NULL,'YES'),
	 ('onec_contacts','contact_channels','jsonb',NULL,'NO'),
	 ('onec_contacts','contact_site','text',NULL,'YES'),
	 ('onec_contacts','contact_address','text',NULL,'YES'),
	 ('onec_contacts','contact_importance_note','text',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','owner_entity','text',NULL,'NO'),
	 ('onec_owners','owner_ref_key','uuid',NULL,'NO'),
	 ('onec_owners','owner_name','text',NULL,'YES'),
	 ('onec_owners','owner_inn','text',NULL,'YES'),
	 ('onec_owners','owner_group','text',NULL,'YES'),
	 ('onec_owners','owner_tags','jsonb',NULL,'NO'),
	 ('onec_owners','owner_notes','text',NULL,'YES'),
	 ('onec_owners','owner_address','text',NULL,'YES'),
	 ('onec_owners','owner_site','text',NULL,'YES'),
	 ('onec_owners','raw_payload','jsonb',NULL,'NO');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','fetched_at','timestamp with time zone',NULL,'NO'),
	 ('onec_owners','owner_source_entity','text',NULL,'YES'),
	 ('onec_owners','owner_status','text',NULL,'YES'),
	 ('onec_owners','owner_is_folder','boolean',NULL,'YES'),
	 ('onec_owners','owner_is_buyer','boolean',NULL,'YES'),
	 ('onec_owners','owner_is_supplier','boolean',NULL,'YES'),
	 ('onec_owners','owner_classification','text',NULL,'YES'),
	 ('onec_owners','owner_is_junk','boolean',NULL,'NO'),
	 ('onec_owners','owner_junk_reason','text',NULL,'YES'),
	 ('onec_owners','owner_converted_to_customer','boolean',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','owner_search_emails','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_search_phones','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_display_name','text',NULL,'YES'),
	 ('onec_owners','owner_company_name','text',NULL,'YES'),
	 ('onec_owners','owner_topic','text',NULL,'YES'),
	 ('onec_owners','owner_source_key','uuid',NULL,'YES'),
	 ('onec_owners','owner_group_path','text',NULL,'YES'),
	 ('onec_owners','owner_tags_text','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_sites','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_addresses','jsonb',NULL,'NO');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','owner_contact_names','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_contact_count','integer',NULL,'NO'),
	 ('onec_owners','owner_contact_emails','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_contact_phones','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_all_emails','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_all_phones','ARRAY',NULL,'NO'),
	 ('onec_owners','owner_notes_compiled','text',NULL,'YES'),
	 ('onec_owners','owner_is_important','boolean',NULL,'NO'),
	 ('onec_owners','owner_importance_score','integer',NULL,'NO'),
	 ('onec_owners','owner_importance_reason','text',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','ai_client_segment','text',NULL,'YES'),
	 ('onec_owners','ai_email_summary','text',NULL,'YES'),
	 ('onec_owners','sent_articles_history','ARRAY',NULL,'YES'),
	 ('onec_owners','last_contact_date','timestamp without time zone',NULL,'YES'),
	 ('onec_owners','owner_created_at','timestamp with time zone',NULL,'YES'),
	 ('onec_owners','owner_updated_at','timestamp with time zone',NULL,'YES'),
	 ('onec_owners','owner_converted_to_customer_1c','boolean',NULL,'YES'),
	 ('onec_owners','owner_contacts_transferred','boolean',NULL,'YES'),
	 ('onec_owners','owner_converted_detected_by_text','boolean',NULL,'YES'),
	 ('onec_owners','owner_raw_converted_value','text',NULL,'YES');
INSERT INTO information_schema.columns (table_name,column_name,data_type,character_maximum_length,is_nullable) VALUES
	 ('onec_owners','owner_raw_contacts_transferred_value','text',NULL,'YES'),
	 ('onec_owners','buyer_order_found','boolean',NULL,'YES'),
	 ('onec_owners','buyer_order_ref_key','uuid',NULL,'YES'),
	 ('onec_owners','buyer_ref_key','uuid',NULL,'YES'),
	 ('onec_owners','buyer_name','text',NULL,'YES');
