[Interface]
PrivateKey = iNaflWhN/ohC97ucNp+qrdvhEO7R3VF6GixG//OeR3A=
Address = 10.10.0.9/32
DNS = 10.10.0.1

[Peer]
PublicKey = RL0dKV7TqTfyiMd61AHleaMvad/jPXvmg54D3rIt0gU=
Endpoint = 109.248.170.181:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
